name = "jai-besoin-de"
main = "src/entry.js"
compatibility_date = "2026-09-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = true
preview_urls = true

[build]
command = "npm run db:init:remote"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "jai-besoin-de-db"
database_id = "47e10f3e-bb3c-4a5b-970d-5f0286b70814"

[vars]
APP_NAME = "J’ai besoin de..."
WEB3FORMS_KEY = "36e8a736-1df0-4aa9-8d60-d0c32868c7e5"
MAIL_FROM = "notifications@VOTRE-DOMAINE.fr"
EVENTS_API_URL = "https://france-evasion-regions.com/api/open/evenements.json"
OVERPASS_URL = "https://overpass-api.de/api/interpreter"
TRANSPORT_DATASET_SLUG_SETRAM = "gtfs-du-reseau-des-transports-bus-et-tramway-setram-circulant-sur-le-territoire-le-mans-metropole"

[triggers]
crons = ["*/15 * * * *", "17 3 * * *"]
